name = "Modpack"
author = "Redacted"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a0bc50e579c92d4d01238a91934c1b01eab5e0afbbcd8647dca23fae9deb9df"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
