name = "Modpack"
author = "Redacted"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20654a205d51ebb5e926ac0a58abda7b8d3d82356ea7c532eeea8ef3ae1b87d9"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.8"]
