name = "Modpack"
author = "Redacted"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be23eb583ae75bbadfdce7a886bf1cdde91db554c2e14539dca6f022fa570779"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
